<?php

namespace app\controllers;

use Yii;
use app\models\Post;
use yii\filters\auth\HttpBasicAuth;

class PostController extends \yii\rest\ActiveController
{

    public $modelClass = 'app\models\Post';

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => HttpBasicAuth::class,
        ];
        return $behaviors;
    }

    public function verbs()
    {
        $verbs = parent::verbs();
        $verbs['create-post'] = ['POST'];

        return $verbs;// TODO: Change the autogenerated stub
    }

    public function actionCreatePost()
    {
        $post = new Post();
        if ($post->load(Yii::$app->request->post(), '') && $post->save()) {
            return [
                'message' => 'Post Added Successfully'
            ];
        } else {
            return $post;
        }
    }
}