<?php

namespace app\controllers;

use app\models\Category;
use app\models\Post;
use Yii;
use yii\filters\auth\HttpBasicAuth;

class PostController extends \yii\rest\ActiveController {

    public $modelClass = 'app\models\Post';

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => HttpBasicAuth::class,
        ];
        return $behaviors;
    }

    public function verbs()
    {
        $verbs = parent::verbs();
        $verbs['create-post'] = ['POST'];


        return  $verbs;// TODO: Change the autogenerated stub
    }


    public function actionCreatePost()
    {
        $category_id = Yii::$app->request->post('category_id');
        $sub_category_id = Yii::$app->request->post('sub_category_id');
        $price = Yii::$app->request->post('price');
        $mobile = Yii::$app->request->post('mobile');

        $post = new Post(
            [
                'category_id' => $category_id,
                'sub_category_id' =>$sub_category_id ,
                'price' =>$price ,
                'mobile' =>$mobile ,
        ]);

        if ($post->validate('mobile')) {
            $category = Category::find()->andWhere(['id' => $category_id])->all();
            $sub_category = Category::find()->andWhere([
                'id' => $sub_category_id,
                'parent_id' => $category_id,
            ])->all();

            if (!empty($category) && !empty($sub_category)) {
                Yii::$app->db->createCommand()->insert(
                    'post',
                    [
                        'category_id' => $category_id,
                        'sub_category_id' =>$sub_category_id ,
                        'price' =>$price ,
                        'mobile' =>$mobile ,
                    ]
                )->execute();

                return 'Post Added Successfully';
            } else {
                return 'Category id or Sub Category id aren\'t exist';
            }
        } else {
            return 'Wrong number pattern Please insert a valid number 07********';
        }

    }

}